// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxt6l7xAJNuq0xcxo-HzslS74w6gIh-Us',
    appId: '1:195827014777:web:b40c0cbd804977711648a8',
    messagingSenderId: '195827014777',
    projectId: 'pizza-delivery-502ae',
    authDomain: 'pizza-delivery-502ae.firebaseapp.com',
    storageBucket: 'pizza-delivery-502ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDs2k0Q9eST0HmdpUSdNmjLIPZwBJtWpI',
    appId: '1:195827014777:android:529f525036502b811648a8',
    messagingSenderId: '195827014777',
    projectId: 'pizza-delivery-502ae',
    storageBucket: 'pizza-delivery-502ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNkWUGR7RCf-KXyX_Ry1wQYCXgGEmi44',
    appId: '1:195827014777:ios:42d933673b4e08a61648a8',
    messagingSenderId: '195827014777',
    projectId: 'pizza-delivery-502ae',
    storageBucket: 'pizza-delivery-502ae.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcNkWUGR7RCf-KXyX_Ry1wQYCXgGEmi44',
    appId: '1:195827014777:ios:42d933673b4e08a61648a8',
    messagingSenderId: '195827014777',
    projectId: 'pizza-delivery-502ae',
    storageBucket: 'pizza-delivery-502ae.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxt6l7xAJNuq0xcxo-HzslS74w6gIh-Us',
    appId: '1:195827014777:web:ff334957804676211648a8',
    messagingSenderId: '195827014777',
    projectId: 'pizza-delivery-502ae',
    authDomain: 'pizza-delivery-502ae.firebaseapp.com',
    storageBucket: 'pizza-delivery-502ae.appspot.com',
  );
}
