name: pizza_repository
description: "The Repo that handles pizzas"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_auth: ^4.19.3
  cloud_firestore: ^4.17.1
  firebase_storage: ^11.7.3
  rxdart: ^0.27.7
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
